### ISSUE TITLE
Package Control on macOS doesn't list Okami

### ISSUE THREAD

**Issue by ghost** [Rayraegah/okami#3]
I get this message on the latest Sublime 3
Package Control: The package "Okami – Adaptive Color Schemes" is either not available on this platform or for this version of Sublime Text

**Comment by Rayraegah** [comment]
Which operating system do you run Sublime Text 3 on? Also, could you tell me your Sublime Text build version number? (This is available in the About Sublime Text dialog box)

**Comment by ghost** [comment]
macOS 10.13.6
Sublime v3. Build 3175
