### ISSUE TITLE
For another ed

### ISSUE THREAD

**Issue by Alexey-T** [Rayraegah/okami#4]
Is it easy to create such color schemes for CudaText too? Tks

**Comment by Rayraegah** [comment]
I haven't used CudaText at all. If it accepts yml or xml style declaration then it's easy to port. Otherwise, it can be created from the base styles.

**Comment by Rayraegah** [comment]
@Alexey-T Just a note, some of the features like _adaptive_ colors and [hashed syntax highlighting](https://www.sublimetext.com/docs/3/color_schemes.html#hashed_syntax_highlighting)  are sublime text specific. Such features may not work when ported for other editors.
